### ISSUE TITLE
R3 in Ecco-group repo

### ISSUE THREAD

**Issue by christophernhill** [gaelforget/ECCO_v4_r2#10]
@gaelforget 

https://github.com/ECCO-GROUP/model-configurations/

fork is a few tags behind gaelforget/ECCOv4 - is it OK to bring it up to date?

**Comment by gaelforget** [comment]
Yes. Thanks. Once master is updated, please merge that into the release2 branch @ <https://github.com/ECCO-GROUP/model-configurations/>. Then maybe e.g. @owang01 would update master according to release3, create a release3 branch, update master according to release4 when ready, and so on and so forth. Does that make sense?
